version: '2'

services:
  app:
    image: 'spring-crud-hibernate:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - app-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  app-db:
    image: 'postgres:13.1-alpine'
    container_name: app-db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres